### ISSUE TITLE
What's the meaning of args.layer_name?

### ISSUE THREAD

**Issue by ayumiymk** [taotaoorange/words-matter-scene-text-for-image-classification#1]
Firstly, I am very grateful for sharing the code.

But I am not clear what's the meaning of args.layer_name in deep_visual_features/extract_googlenet_feat.py? Could you please show the usage of it?

Thanks!

**Comment by taotaoorange** [comment]
That is the name of the layer, "pool5/7x7_s1", the output of which is used as the feature.

**Comment by ayumiymk** [comment]
OK, thanks. 

What's more, in your paper, "Words matter ...", you say you l2 normalized the visual features before classification, but I don't find the related code snippet. Does it matter?

**Comment by taotaoorange** [comment]
I never tried unnormalized.

**Comment by ayumiymk** [comment]
Thanks.
