### ISSUE TITLE
How about the code of visual and textual fusion?

### ISSUE THREAD

**Issue by ayumiymk** [taotaoorange/words-matter-scene-text-for-image-classification#2]
Hi Tao,

In your released code and Readme, I don't find the code about two cues fusion and the textual classifier. I am new to Matlab and some Matlab-based third-party-library. Could you please release these codes?

Thanks!

**Comment by taotaoorange** [comment]
run_classification.m shows the classification given the pre-computed kernel matrix. Fusion is simply adding the two kernel matrices, one from visual features and one from features of textual contents.

**Comment by ayumiymk** [comment]
Thanks for your reply! But how to get the pre-computed kernel matrix? I have extracted textual and visual features. But I don't know how to use them now.

**Comment by weitingyuk** [comment]
Hi tao,
Thanks for sharing the code.I have extracted textual and visual features too,
and I have the same question. How to use them? How to get the pre-computed kernel matrix?
Could you share all the code?
Thanks!

**Comment by taotaoorange** [comment]
Let n-by-k matrix X be the features. n is the number of samples and k is the dimensionality of the feature. The features are L2 normalized. 
The kernel matrix K, which is an n-by-n matrix,  can be computed by K = X * X'

Let K1 be the kernel computed from visual features and K2 be the kernel matrix computed from textual features. Fusion is simply by K = K1 + K2.
