### ISSUE TITLE
A bug in run_classification.m

### ISSUE THREAD

**Issue by ayumiymk** [taotaoorange/words-matter-scene-text-for-image-classification#3]
Hi Tao,

I find there is a bug in `run_classification.m`. 
```
[predicted_label, accuracy, decision_values] = svmpredict(labels_t, [(1:length(testImageNames))' K(f_test,f_train)], model);
```
should be changed into
```
[predicted_label, accuracy, decision_values] = svmpredict(double(labels_t), [(1:length(testImageNames))' double(K(f_test,f_train))], model);
```
Otherwise, there is an error: `Error: label vector and instance matrix must be double`.

**Comment by weitingyuk** [comment]
@ayumiymk hi, can you run the file of run_classification.m? Would you share your kernel k?
